services:
  # Frontend - Next.js React Application
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: techcorp-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - techcorp-network

  # Backend - Flask API Server
  backend:
    build:
      context: ../backend
      dockerfile: ../config/Dockerfile
    container_name: techcorp-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=techcorp_jwt_secret_2024
      - ADMIN_TOKEN=admin_secret_token_12345
    depends_on:
      - redis
    volumes:
      - ../logs:/app/logs
    networks:
      - techcorp-network

  # Redis - Data Store
  redis:
    image: redis:7-alpine
    container_name: techcorp-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - techcorp-network
    # No external ports - internal only

  # Nginx - Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: techcorp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - techcorp-network

networks:
  techcorp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

volumes:
  redis_data:
    driver: local